# .github/workflows/auto_model_training.yml
name: Model Training

on:
  repository_dispatch:
    types: [run-training]
  workflow_dispatch:  # Allow manual triggering

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Need history to check changes
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas torch faiss-cpu tqdm scikit-learn matplotlib
      
      # MODEL TRAINING
      - name: Run Model Training
        id: training
        run: |
          echo "Starting model training..."
          python src/main.py \
            --data_path data/processed/recommender_data.csv \
            --output_dir output \
            --mode train \
            --epochs 5 \
            --batch_size 20 \
            --embedding_dim 32
      
      # COMMIT UPDATED MODELS
      - name: Configure Git LFS
        if: success()
        run: |
          git lfs install
      
      - name: Commit updated models
        if: success()
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add output/user_model.pth output/item_model.pth output/item_embeddings.npy 
          git add output/ann_index.faiss output/ann_index.meta.npy output/training_history.json
          git commit -m "Update models based on dataset changes [skip ci]" || echo "No changes to commit"
          git push